# Playbook to call multiple roles to configure systems
- name: Configure systems
  hosts: 52.47.136.17
  become: yes

  tasks:

- name: Call Roles
  hosts: 52.47.136.17
  roles:
   #- hostname
   #- firewalld
   #- ntp-config
   - motd
